[package]
name = "sandbox"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "main"
path = "src/rust/main.rs"

[[test]]
name = "integration"
path = "src/rust/tests/main.rs"

[dev-dependencies]
test-generator = "0.3.0"
