#!/usr/bin/env node
// Post-commit cherry pick

const { execSync } = require('child_process');
const excludePick = require('../cherryignore.json');
const commit = execSync('git rev-parse --short HEAD');

// only cherry pick if commit was in main
try {
	execSync(`git log main | grep ${commit}`);
} catch {
	process.exit(0);
}

execSync('git checkout deploy');
const commitFiles = execSync(`git diff-tree --no-commit-id --name-only -r ${commit}`).toString().split('\n');
if (commitFiles.some(item => excludePick.includes(item))) {
	// disallow cherry pick if the files in branches should be different 
	execSync(`git cherry-pick -S --allow-empty -X theirs -n ${commit} `);
	process.exit(0);
} else {
	execSync(`git cherry-pick -S --allow-empty -X theirs ${commit} `);
}
execSync('git checkout main');